/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAlert: typeof import('ant-design-vue/es')['Alert']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACol: typeof import('ant-design-vue/es')['Col']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AFlex: typeof import('ant-design-vue/es')['Flex']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AModal: typeof import('ant-design-vue/es')['Modal']
    AppNav: typeof import('./src/components/layout/AppNav.vue')['default']
    ARadio: typeof import('ant-design-vue/es')['Radio']
    ARadioButton: typeof import('ant-design-vue/es')['RadioButton']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASegmented: typeof import('ant-design-vue/es')['Segmented']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASlider: typeof import('ant-design-vue/es')['Slider']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATag: typeof import('ant-design-vue/es')['Tag']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    AuthModal: typeof import('./src/components/auth/AuthModal.vue')['default']
    BasketballScoreBoard: typeof import('./src/components/basketball/BasketballScoreBoard.vue')['default']
    LiveMatchesCarousel: typeof import('./src/components/home/LiveMatchesCarousel.vue')['default']
    LiveSyncStatus: typeof import('./src/components/LiveSyncStatus.vue')['default']
    NavDropdown: typeof import('./src/components/layout/NavDropdown.vue')['default']
    OperatorCloseGuardBanner: typeof import('./src/components/OperatorCloseGuardBanner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScoreBoard: typeof import('./src/components/ScoreBoard.vue')['default']
    ShortcutKeyInput: typeof import('./src/components/settings/ShortcutKeyInput.vue')['default']
    SportPicker: typeof import('./src/components/sport/SportPicker.vue')['default']
    TournamentStandingsPanel: typeof import('./src/components/tournament/TournamentStandingsPanel.vue')['default']
  }
}
